### ISSUE TITLE
Search input gets defocused after initial search result fetching

### ISSUE THREAD

**Issue by KubaJastrz** [Tryfciu/spacer-app#6]
As show in the gif below, text inputs loses focus after initial data fetching. I believe it should keep focus unless user clicks on one of the images.

![peek 2018-10-28 20-49](https://user-images.githubusercontent.com/6443113/47621105-0fb18380-daf3-11e8-846d-c914c96b95ab.gif)

**Comment by Tryfciu** [comment]
Yeah, you are right. Right now  I don't really know why it behaves like that, but I will try to troubleshoot and quickly resolve the issue. Thank you for reporting the bug. :crown: :muscle: :+1:
